version: '3.3'

services:
  dbmultiuser:
    image: mysql:5.7.26
    restart: always
    environment:
      MYSQL_DATABASE: 'multi.user.roles'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3310:3306'
    expose:
      - '3307'
    volumes:
      - cms-db:/var/lib/mysql
# Names our volume
volumes:
  cms-db:
